name: Android Building

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Unsigned Release APK with Gradle
        run: bash ./gradlew assembleRelease --stacktrace
        
      - name: Get apk path
        id: apk-path
        run: echo "path=$(find . -regex '^.*/build/outputs/apk/.*\.apk$' -type f | head -1)" >> $GITHUB_OUTPUT
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tordroid
          path: ./wallet/build/outputs/apk/release/wallet-release-unsigned.apk
