name: Android Building

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Unsigned Release APK with Gradle
        run: bash ./gradlew assembleRelease --stacktrace
        
      - name: Get apk path
        id: apk-path
        run: echo "path=$(find . -regex '^.*/build/outputs/apk/.*\.apk$' -type f | head -1)" >> $GITHUB_OUTPUT
      - name: Get apk info
        id: apk-info
        uses: hkusu/apk-info-action@v1
        with:
          apk-path: ${{ steps.apk-path.outputs.path }}
      - name: Show apk info
        run: |
          echo '${{ steps.apk-info.outputs.application-name }}'
          echo '${{ steps.apk-info.outputs.application-id }}'
          echo '${{ steps.apk-info.outputs.version-code }}'
          echo '${{ steps.apk-info.outputs.version-name }}'
          echo '${{ steps.apk-info.outputs.min-sdk-version }}'
          echo '${{ steps.apk-info.outputs.target-sdk-version }}'
          echo '${{ steps.apk-info.outputs.compile-sdk-version }}'
          echo '${{ steps.apk-info.outputs.uses-permissions }}'
          echo '${{ steps.apk-info.outputs.debuggable }}'
          echo '${{ steps.apk-info.outputs.allow-backup }}'
          echo '${{ steps.apk-info.outputs.supports-rtl }}'
          echo '${{ steps.apk-info.outputs.file-size }}'
          echo '${{ steps.apk-info.outputs.readable-file-size }}'
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tordroid
          path: tordroid/build/outputs/apk/release/*.apk
